// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: dependencies.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const createDependency = `-- name: CreateDependency :one
INSERT INTO dependencies (project_id, from_task_id, to_task_id)
VALUES ($1, $2, $3)
RETURNING id, project_id, from_task_id, to_task_id
`

type CreateDependencyParams struct {
	ProjectID  uuid.UUID `json:"projectId"`
	FromTaskID uuid.UUID `json:"fromTaskId"`
	ToTaskID   uuid.UUID `json:"toTaskId"`
}

func (q *Queries) CreateDependency(ctx context.Context, arg CreateDependencyParams) (Dependency, error) {
	row := q.db.QueryRow(ctx, createDependency, arg.ProjectID, arg.FromTaskID, arg.ToTaskID)
	var i Dependency
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.FromTaskID,
		&i.ToTaskID,
	)
	return i, err
}

const deleteDependency = `-- name: DeleteDependency :exec
DELETE FROM dependencies
WHERE id = $1
`

func (q *Queries) DeleteDependency(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteDependency, id)
	return err
}

const getDependencyProjectID = `-- name: GetDependencyProjectID :one
SELECT project_id
FROM dependencies
WHERE id = $1
`

func (q *Queries) GetDependencyProjectID(ctx context.Context, id uuid.UUID) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, getDependencyProjectID, id)
	var project_id uuid.UUID
	err := row.Scan(&project_id)
	return project_id, err
}

const listDependenciesByProject = `-- name: ListDependenciesByProject :many
SELECT id, project_id, from_task_id, to_task_id
FROM dependencies
WHERE project_id = $1
`

func (q *Queries) ListDependenciesByProject(ctx context.Context, projectID uuid.UUID) ([]Dependency, error) {
	rows, err := q.db.Query(ctx, listDependenciesByProject, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Dependency{}
	for rows.Next() {
		var i Dependency
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.FromTaskID,
			&i.ToTaskID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDependencyEdgesByProject = `-- name: ListDependencyEdgesByProject :many
SELECT from_task_id, to_task_id
FROM dependencies
WHERE project_id = $1
`

type ListDependencyEdgesByProjectRow struct {
	FromTaskID uuid.UUID `json:"fromTaskId"`
	ToTaskID   uuid.UUID `json:"toTaskId"`
}

func (q *Queries) ListDependencyEdgesByProject(ctx context.Context, projectID uuid.UUID) ([]ListDependencyEdgesByProjectRow, error) {
	rows, err := q.db.Query(ctx, listDependencyEdgesByProject, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListDependencyEdgesByProjectRow{}
	for rows.Next() {
		var i ListDependencyEdgesByProjectRow
		if err := rows.Scan(&i.FromTaskID, &i.ToTaskID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
