// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: invites.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createInvite = `-- name: CreateInvite :exec
INSERT INTO invites (token, project_id, created_by, expires_at)
VALUES ($1, $2, $3, $4)
`

type CreateInviteParams struct {
	Token     string             `json:"token"`
	ProjectID uuid.UUID          `json:"projectId"`
	CreatedBy uuid.UUID          `json:"createdBy"`
	ExpiresAt pgtype.Timestamptz `json:"expiresAt"`
}

func (q *Queries) CreateInvite(ctx context.Context, arg CreateInviteParams) error {
	_, err := q.db.Exec(ctx, createInvite,
		arg.Token,
		arg.ProjectID,
		arg.CreatedBy,
		arg.ExpiresAt,
	)
	return err
}

const getInvite = `-- name: GetInvite :one
SELECT project_id, expires_at
FROM invites
WHERE token = $1
`

type GetInviteRow struct {
	ProjectID uuid.UUID          `json:"projectId"`
	ExpiresAt pgtype.Timestamptz `json:"expiresAt"`
}

func (q *Queries) GetInvite(ctx context.Context, token string) (GetInviteRow, error) {
	row := q.db.QueryRow(ctx, getInvite, token)
	var i GetInviteRow
	err := row.Scan(&i.ProjectID, &i.ExpiresAt)
	return i, err
}
