// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: tasks.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createTask = `-- name: CreateTask :one
INSERT INTO tasks (project_id, title, status, assignee_id, x, y, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, now())
RETURNING id, project_id, title, status, assignee_id, x, y, updated_at
`

type CreateTaskParams struct {
	ProjectID  uuid.UUID  `json:"projectId"`
	Title      string     `json:"title"`
	Status     string     `json:"status"`
	AssigneeID *uuid.UUID `json:"assigneeId"`
	X          float64    `json:"x"`
	Y          float64    `json:"y"`
}

type CreateTaskRow struct {
	ID         uuid.UUID          `json:"id"`
	ProjectID  uuid.UUID          `json:"projectId"`
	Title      string             `json:"title"`
	Status     string             `json:"status"`
	AssigneeID *uuid.UUID         `json:"assigneeId"`
	X          float64            `json:"x"`
	Y          float64            `json:"y"`
	UpdatedAt  pgtype.Timestamptz `json:"updatedAt"`
}

func (q *Queries) CreateTask(ctx context.Context, arg CreateTaskParams) (CreateTaskRow, error) {
	row := q.db.QueryRow(ctx, createTask,
		arg.ProjectID,
		arg.Title,
		arg.Status,
		arg.AssigneeID,
		arg.X,
		arg.Y,
	)
	var i CreateTaskRow
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Title,
		&i.Status,
		&i.AssigneeID,
		&i.X,
		&i.Y,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteTask = `-- name: DeleteTask :exec
DELETE FROM tasks
WHERE id = $1
`

func (q *Queries) DeleteTask(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteTask, id)
	return err
}

const getTask = `-- name: GetTask :one
SELECT id, project_id, title, status, assignee_id, x, y, updated_at
FROM tasks
WHERE id = $1
`

type GetTaskRow struct {
	ID         uuid.UUID          `json:"id"`
	ProjectID  uuid.UUID          `json:"projectId"`
	Title      string             `json:"title"`
	Status     string             `json:"status"`
	AssigneeID *uuid.UUID         `json:"assigneeId"`
	X          float64            `json:"x"`
	Y          float64            `json:"y"`
	UpdatedAt  pgtype.Timestamptz `json:"updatedAt"`
}

func (q *Queries) GetTask(ctx context.Context, id uuid.UUID) (GetTaskRow, error) {
	row := q.db.QueryRow(ctx, getTask, id)
	var i GetTaskRow
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Title,
		&i.Status,
		&i.AssigneeID,
		&i.X,
		&i.Y,
		&i.UpdatedAt,
	)
	return i, err
}

const getTaskProjectID = `-- name: GetTaskProjectID :one
SELECT project_id
FROM tasks
WHERE id = $1
`

func (q *Queries) GetTaskProjectID(ctx context.Context, id uuid.UUID) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, getTaskProjectID, id)
	var project_id uuid.UUID
	err := row.Scan(&project_id)
	return project_id, err
}

const listTasksByProject = `-- name: ListTasksByProject :many
SELECT id, project_id, title, status, assignee_id, x, y, updated_at
FROM tasks
WHERE project_id = $1
ORDER BY created_at
`

type ListTasksByProjectRow struct {
	ID         uuid.UUID          `json:"id"`
	ProjectID  uuid.UUID          `json:"projectId"`
	Title      string             `json:"title"`
	Status     string             `json:"status"`
	AssigneeID *uuid.UUID         `json:"assigneeId"`
	X          float64            `json:"x"`
	Y          float64            `json:"y"`
	UpdatedAt  pgtype.Timestamptz `json:"updatedAt"`
}

func (q *Queries) ListTasksByProject(ctx context.Context, projectID uuid.UUID) ([]ListTasksByProjectRow, error) {
	rows, err := q.db.Query(ctx, listTasksByProject, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTasksByProjectRow{}
	for rows.Next() {
		var i ListTasksByProjectRow
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Title,
			&i.Status,
			&i.AssigneeID,
			&i.X,
			&i.Y,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTask = `-- name: UpdateTask :one
UPDATE tasks
SET
    title = $2,
    status = $3,
    assignee_id = $4,
    x = $5,
    y = $6,
    updated_at = now()
WHERE id = $1
RETURNING id, project_id, title, status, assignee_id, x, y, updated_at
`

type UpdateTaskParams struct {
	ID         uuid.UUID  `json:"id"`
	Title      string     `json:"title"`
	Status     string     `json:"status"`
	AssigneeID *uuid.UUID `json:"assigneeId"`
	X          float64    `json:"x"`
	Y          float64    `json:"y"`
}

type UpdateTaskRow struct {
	ID         uuid.UUID          `json:"id"`
	ProjectID  uuid.UUID          `json:"projectId"`
	Title      string             `json:"title"`
	Status     string             `json:"status"`
	AssigneeID *uuid.UUID         `json:"assigneeId"`
	X          float64            `json:"x"`
	Y          float64            `json:"y"`
	UpdatedAt  pgtype.Timestamptz `json:"updatedAt"`
}

func (q *Queries) UpdateTask(ctx context.Context, arg UpdateTaskParams) (UpdateTaskRow, error) {
	row := q.db.QueryRow(ctx, updateTask,
		arg.ID,
		arg.Title,
		arg.Status,
		arg.AssigneeID,
		arg.X,
		arg.Y,
	)
	var i UpdateTaskRow
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Title,
		&i.Status,
		&i.AssigneeID,
		&i.X,
		&i.Y,
		&i.UpdatedAt,
	)
	return i, err
}
